### ISSUE TITLE
Problems on mobile interfaces

### ISSUE THREAD

**Issue by denizdogan** [reinvanoyen/tnt-carousel#3]
I'm working on a project where I'd like to use this carousel plugin, but when the user wants to scroll the page and starts the touch event on the carousel, they only end up scrolling the carousel a few pixels on the X axis.

I'm not sure what the best way would be to fix this.

**Comment by reinvanoyen** [comment]
Just to get this clear, the user wants to scroll vertically, but ends up swiping horizontally in the carousel, right? If that's the problem you're facing, I'll fix it as soon as possible.

I haven't been developing this carousel for a while now and see some major improvements that are still to do. Nonetheless I'm very happy someone is using it, this give me a boost to keep developing it. If you want to help out, you are very welcome to do so!

**Comment by denizdogan** [comment]
Yeah, you understood me perfectly! Thanks

**Comment by reinvanoyen** [comment]
This bug is fixed in 1.3.0. Vertical scrolling in the page should be possible on mobile. Please let me know if it works as desired.
